<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Mapster" Version="7.4.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\EMSI.Fuga.Config\EMSI.Fuga.Config.csproj" />
      <ProjectReference Include="..\EMSI.Fuga.Domain.Abstractions\EMSI.Fuga.Domain.Abstractions.csproj" />
      <ProjectReference Include="..\EMSI.Fuga.Infrastructure.Database\EMSI.Fuga.Infrastructure.Database.csproj" />
      <ProjectReference Include="..\EMSI.Fuga.Presentation.Dto\EMSI.Fuga.Presentation.Dto.csproj" />
      <ProjectReference Include="..\EMSI.Fuga\EMSI.Fuga.csproj" />
    </ItemGroup>

</Project>
